package net.ty.createcraftedbeginning.config;

import net.createmod.catnip.config.ConfigBase;
import org.jetbrains.annotations.NotNull;

@SuppressWarnings("unused")
public class CCBAirtights extends ConfigBase {
    public final ConfigGroup airCompressor = group(0, "air_compressor", "Air Compressor");
    public final ConfigInt nextOverheatThreshold = i(1200, 20, "next_overheat_threshold", Comments.gameTicks, Comments.nextOverheatThreshold);
    public final ConfigInt pressurizationRateMultiplier = i(4, 1, "pressurization_rate_multiplier", Comments.pressurizationRateMultiplier);
    public final ConfigBool explodesOnMeltdown = b(true, "explodes_on_meltdown", Comments.explodesOnMeltdown);

    public final ConfigGroup airtightAssemblyDriver = group(0, "airtight_assembly_driver", "Airtight Assembly Driver");
    public final ConfigInt residueFailureCooldown = i(120, 20, "residue_failure_cooldown", Comments.gameTicks, Comments.residueFailureCooldown);
    public final ConfigInt residueGenerationCooldown = i(12, 1, "residue_generation_cooldown", Comments.gameTicks, Comments.residueGenerationCooldown);
    public final ConfigInt consecutiveSuccessesCount = i(20, 1, "consecutive_successes_count", Comments.consecutiveSuccessesCount);
    public final ConfigInt itemQuantityMultiplier = i(8, 1, 64, "item_quantity_multiplier", Comments.itemQuantityMultiplier);
    public final ConfigInt fluidQuantityMultiplier = i(8, 1, 512, "fluid_quantity_multiplier", Comments.fluidQuantityMultiplier);

    public final ConfigGroup airtightHatch = group(0, "airtight_hatch", "Airtight Hatch");
    public final ConfigInt maxTransferRate = i(5, 1, "max_transfer_rate", Comments.milliBuckets, Comments.maxTransferRate);

    public final ConfigGroup airtightPump = group(0, "airtight_pump", "Airtight Pump");
    public final ConfigInt maxPumpRange = i(32, 1, "max_pump_range", Comments.blocks, Comments.maxPumpRange);

    public final ConfigGroup airtightEncasedPipe = group(0, "airtight_encased_pipe", "Airtight Encased Pipe");
    public final ConfigBool canSealWithoutSheets = b(true, "can_seal_without_sheets", Comments.canSealWithoutSheets);

    public final ConfigGroup gasCanister = group(0, "gas_canister", "Gas Canister");
    public final ConfigInt maxCanisterCapacity = i(20, 1, "max_canister_capacity", Comments.buckets, Comments.maxCanisterCapacity);

    public final ConfigGroup breezeChamber = group(0, "breeze_chamber", "Breeze Chamber");
    public final ConfigInt maxEnergizationRate = i(1000, 1, "max_energization_rate", Comments.milliBuckets, Comments.maxEnergizationRate);

    public final ConfigGroup worldSettings = group(0, "world_settings", "World Settings");
    public final ConfigBool canExtractAirFromWorld = b(true, "canExtractAirFromWorld", Comments.canExtractAirFromWorld);
    public final ConfigBool canCoolerGetFromSpawners = b(true, "canCoolerGetFromSpawners", Comments.canCoolerGetFromSpawners);

    @Override
    public @NotNull String getName() {
        return "airtights";
    }

    private static class Comments {
        static String gameTicks = "[in game ticks]";
        static String blocks = "[in Blocks]";
        static String buckets = "[in Buckets]";
        static String milliBuckets = "[in milli-Buckets]";
        static String canCoolerGetFromSpawners = "Allows using an Empty Breeze Cooler on Spawners and Trial Spawners to obtain a Breeze Cooler with Breeze.";
        static String canExtractAirFromWorld = "Allows opened pipes to extract air from the environment.";
        static String canSealWithoutSheets = "Allow sealing Airtight Casing Pipe openings without holding an Airtight Sheet.";
        static String consecutiveSuccessesCount = "The number of consecutive successful Residue Generations required for the Airtight Assembly Driver to increase its Residue Level.";
        static String explodesOnMeltdown = "Whether the Air Compressor explodes upon entering Meltdown state. If explosion is disabled, it will only be destroyed without exploding.";
        static String fluidQuantityMultiplier = "The quantity multiplier for Fluid Residue generated by the Airtight Assembly Driver.";
        static String itemQuantityMultiplier = "The quantity multiplier for Item Residue generated by the Airtight Assembly Driver.";
        static String maxCanisterCapacity = "The maximum gas capacity of the Gas Canister, which also determines the capacity of many other gas containers.";
        static String maxEnergizationRate = "The maximum per-second energization rate of the Breeze Chamber.";
        static String maxPumpRange = "The maximum distance an Airtight Pump can push or pull gas on either side.";
        static String maxTransferRate = "The maximum per-second transfer rate of the Airtight Hatch.";
        static String nextOverheatThreshold = "The time required for the Air Compressor to advance to the next overheat state.";
        static String pressurizationRateMultiplier = "The pressurization rate multiplier of the Air Compressor when pressurizing gases.";
        static String residueFailureCooldown = "The cooldown period applied to the Airtight Assembly Driver when decreases its Residue Level due to residue generation failure.";
        static String residueGenerationCooldown = "The cooldown period between each Residue generation attempt by the Airtight Assembly Driver.";
    }
}
