package net.ty.createcraftedbeginning.config;

import net.createmod.catnip.config.ConfigBase;
import org.jetbrains.annotations.NotNull;

public class CCBCompressedAir extends ConfigBase {
    public final ConfigFloat airAmountFromIntakePort = f(.8f, 0, "airAmountFromIntakePort", Comments.milliBuckets, Comments.airAmountFromIntakePort);
    public final ConfigInt airtightTankCapacity = i(80, 1, "airtightTankCapacity", Comments.buckets, Comments.airtightTankCapacity);
    public final ConfigBool canChamberGetFromSpawners = b(true, "canChamberGetFromSpawners", Comments.canChamberGetFromSpawners);
    public final ConfigInt canisterCapacity = i(20, 1, "canisterCapacity", Comments.buckets, Comments.canisterCapacity);
    public final ConfigFloat explosionPower = f(2f, 0, 16f, "explosionPower", Comments.explosionPower);
    public final ConfigFloat pressurizationAmount = f(.4f, 0, "pressurizationAmount", Comments.milliBuckets, Comments.pressurizationAmount);
    public final ConfigInt safeAirAmount = i(1, 0, "safeAirAmount", Comments.buckets, Comments.safeAirAmount);
    public final ConfigFloat safeRotationSpeed = f(30, 1, "safeRotationSpeed", Comments.safeRotationSpeed);

    @Override
    public @NotNull String getName() {
        return "compressedAir";
    }

    private static class Comments {
        static String buckets = "[in Buckets]";
        static String milliBuckets = "[in milli-Buckets]";
        static String airAmountFromIntakePort = "The amount of Compressed Air generated by the Airtight Intake Port per tick at 1 RPM.";
        static String airtightTankCapacity = "The amount of Compressed Air a Airtight Tank can hold per block.";
        static String canChamberGetFromSpawners = "Allows to use an empty Breeze Chamber on a Spawner or Trial Spawner to obtain a Breeze Chamber.";
        static String canisterCapacity = "The amount of Compressed Air a Compressed Air Canister can hold per item.";
        static String explosionPower = "Explosion power when Compressed Air ruptures pipes. Set to 0 to disable the explosion behavior.";
        static String pressurizationAmount = "The amount of Compressed Air pressurized by the Air Compressor per tick at 1 RPM.";
        static String safeAirAmount = "The maximum amount of Compressed Air that can be stored in the Fluid Tanks without causing an explosion.";
        static String safeRotationSpeed = "The maximum allowed rotation speed for the Mechanical Pump when pumping Compressed Air without causing an explosion. This value also holds true for Fluid Pipes transporting Compressed Air.";
    }
}
