package net.ty.createcraftedbeginning.config;

import net.createmod.catnip.config.ConfigBase;
import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;

@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
public class CCBClient extends ConfigBase {
    public final ConfigBool enableChestplateFirstPersonArm = b(true, "enable_chestplate_first_person_arm", Comments.enableAirtightChestplateFirstPersonArm);
    public final ConfigBool enableAirtightEncasedPipeOutline = b(true, "enable_airtight_encased_pipe_outline", Comments.enableAirtightEncasedPipeOutline);
    public final ConfigBool enableChestplateJetpackParticles = b(true, "enable_chestplate_jetpack_particles", Comments.enableChestplateJetpackParticles);
    public final ConfigBool enableCurrentGasInfo = b(true, "enable_current_gas_info", Comments.enableCurrentGasInfo);
    public final ConfigBool enableEndIncinerationBlowerOutline = b(true, "enable_end_incineration_blower_outline", Comments.enableEndIncinerationBlowerOutline);
    public final ConfigBool enableEndIncinerationBlowerParticles = b(true, "enable_end_incineration_blower_particles", Comments.enableEndIncinerationBlowerParticles);
    public final ConfigBool enableEndSculkSilencerOutline = b(true, "enable_end_sculk_silencer_outline", Comments.enableEndSculkSilencerOutline);
    public final ConfigBool enableGasAreaOutline = b(true, "enable_gas_area_outline", Comments.enableGasAreaOutline);
    public final ConfigInt gasInfoXOffset = i(0, "gas_info_x_offset", Comments.gasInfoXOffset);
    public final ConfigInt gasInfoYOffset = i(0, "gas_info_y_offset", Comments.gasInfoYOffset);
    public final ConfigInt gasRequestAltScrollStep = i(10, 1, "gas_request_alt_scroll_step", Comments.gasRequestScrollStepAlt);
    public final ConfigInt gasRequestCtrlScrollStep = i(1, 1, "gas_request_ctrl_scroll_step", Comments.gasRequestScrollStepCtrl);
    public final ConfigInt gasRequestScrollStep = i(1000, 1, "gas_request_scroll_step", Comments.gasRequestScrollStep);
    public final ConfigInt gasRequestShiftScrollStep = i(100, 1, "gas_request_shift_scroll_step", Comments.gasRequestScrollStepShift);
    public final ConfigInt maxItemStackDisplay = i(4, 1, 27, "max_item_stack_display", Comments.maxItemStackDisplay);

    @Override
    public String getName() {
        return "client";
    }

    private static class Comments {
        static String enableAirtightChestplateFirstPersonArm = "Whether to render the player's arm in first person while wearing an Airtight Chestplate.";
        static String enableAirtightEncasedPipeOutline = "Whether to display the open and closed sides of an Airtight Encased Pipe while holding a Wrench and wearing Engineer's Goggles.";
        static String enableChestplateJetpackParticles = "Whether to render jetpack particles while flying with an Airtight Chestplate.";
        static String enableCurrentGasInfo = "Whether to display information about the player's currently selected gas supply.";
        static String enableEndIncinerationBlowerOutline = "Whether to display the End Incineration Blower's working range.";
        static String enableEndIncinerationBlowerParticles = "Whether to display particles generated by the End Incineration Blower.";
        static String enableEndSculkSilencerOutline = "Whether to display the chunk columns affected by the End Sculk Silencer.";
        static String enableGasAreaOutline = "Whether to display outlines around areas where gas is being expelled.";
        static String gasInfoXOffset = "The horizontal offset, in pixels, of the current gas display.";
        static String gasInfoYOffset = "The vertical offset, in pixels, of the current gas display.";
        static String gasRequestScrollStep = "The amount by which a gas request changes per scroll step on the Redstone Requester screen.";
        static String gasRequestScrollStepAlt = "The amount by which a gas request changes per scroll step while holding Alt on the Redstone Requester screen.";
        static String gasRequestScrollStepCtrl = "The amount by which a gas request changes per scroll step while holding Ctrl on the Redstone Requester screen.";
        static String gasRequestScrollStepShift = "The amount by which a gas request changes per scroll step while holding Shift on the Redstone Requester screen.";
        static String maxItemStackDisplay = "The maximum number of item stacks shown in tooltips for the Airtight Forging Press and Airtight Reactor Kettle when wearing Engineer's Goggles.";
    }
}
