package net.ty.createcraftedbeginning.config;

import net.createmod.catnip.config.ConfigBase;
import org.jetbrains.annotations.NotNull;

public class CCBServer extends ConfigBase {
    public final CCBStress stressValues = nested(0, CCBStress::new, Comments.stress);
    public final ConfigInt safeAirAmount = i(1, 0, "safeAirAmount", Comments.buckets, Comments.safeAirAmount);
    public final ConfigFloat safeRotationSpeed = f(30, 1, "safeRotationSpeed", Comments.safeRotationSpeed);
    public final ConfigInt airtightTankCapacity = i(80, 1, "airtightTankCapacity", Comments.buckets, Comments.airtightTankCapacity);
    public final ConfigInt airAmountFromIntakePort = i(10, 1, "airAmountFromIntakePort", Comments.milliBuckets, Comments.airAmountFromIntakePort);
    public final ConfigInt pressurizationAmount = i(5, 1, "pressurizationAmount", Comments.milliBuckets, Comments.convertAmount);
    public final ConfigInt canisterCapacity = i(20, 1, "canisterCapacity", Comments.buckets, Comments.canisterCapacity);

    @Override
    public @NotNull String getName() {
        return "server";
    }

    private static class Comments {
        static String buckets = "[in Buckets]";
        static String milliBuckets = "[in milli-Buckets]";
        static String stress = "Fine tune the kinetic stats of individual components.";
        static String safeAirAmount = "The maximum amount of Compressed Air that can be stored in the Fluid Tanks without causing an explosion.";
        static String safeRotationSpeed = "The maximum allowed rotation speed for the Mechanical Pump when pumping Compressed Air without causing an explosion. This value also holds true for Fluid Pipes transporting Compressed Air.";
        static String airtightTankCapacity = "The amount of Compressed Air a Airtight Tank can hold per block.";
        static String airAmountFromIntakePort = "The amount of Compressed Air generated by the Airtight Intake Port per second at 1 RPM.";
        static String convertAmount = "The amount of Compressed Air pressurized by the Air Compressor per second at 1 RPM.";
        static String canisterCapacity = "The amount of Compressed Air a Compressed Air Canister can hold per item.";
    }
}
